
import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  console.warn("API_KEY environment variable not set. Using a placeholder. The app may not function correctly.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const editImageWithMask = async (
  originalImageBase64: string,
  maskImageBase64: string
): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { 
            text: 'Please remove the object in the masked area, and fill the space with a realistic background that matches the surroundings. The white area of the mask indicates the object to remove.' 
          },
          {
            inlineData: {
              data: originalImageBase64.split(',')[1],
              mimeType: 'image/jpeg',
            },
          },
          {
            inlineData: {
              data: maskImageBase64.split(',')[1],
              mimeType: 'image/png',
            },
          },
        ],
      },
      config: {
          responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    
    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error('Error calling Gemini API:', error);
    throw new Error('Failed to edit image. Please check the console for more details.');
  }
};
